### ISSUE TITLE
dates are still in 2019

### ISSUE THREAD

**Issue by sphaero** [PanderMusubi/afvalophaaldata#5]
For the rmn source (i.e. 3764) the published dates are still in 2019.
Running locally has no effect as the update script thinks the cache has not yet expired.
This makes sense as it only checks the mtime of the directory and not the commit date. A fresh clone will always have a very recent mtime.
```
tstamp = path.getmtime(adress_path)
if tstamp > now - 4 * 86400:  # not older than four days
```
Perhaps it's better to use the commit log of the directory, i.e.:
```
$ git log -1 --date=raw --format=format:%ct ics/3764/
1576070418
```

**Comment by PanderMusubi** [comment]
Since a while regular updates have been made.
